### ISSUE TITLE
python3-straight.plugin not in ubuntu 16.04 LTS repos (remove?)

### ISSUE THREAD

**Issue by FoivosMichelinakis** [ana-cc/monroe-cli#12]
It seems that package python3-straight.plugin is in the repo of only in the latest version of ubuntu and not in the repo of the current LTS

https://packages.ubuntu.com/bionic/python3-straight.plugin

By going through the code it seems to me that it is not really needed, since the plugins folder is empty.
Would it make sense to remove this dependency?

**Comment by ana-cc** [comment]
Hi, I initially enabled plugins in the cli as some developers expressed the desire to extend the cli to support specific measurement tools. I'll inquire about whether this is still needed but meanwhile a workaround is to comment out lines 13 and 381-383 in the monroe/cli file and reinstall, the dependency will not be needed.

**Comment by FoivosMichelinakis** [comment]
This is what I am doing for now. I mentioned that just so it is more straightforward for people who use the LTS as well

**Comment by irl** [comment]
@FoivosMichelinakis Of course the plugins folder is empty, this framework is for 3rd-party plugins to integrate with the CLI and the CLI itself does not ship with 3rd-party plugins.

My changes in #13 allow for the CLI to work while disabling 3rd-party plugin support on older systems. The next Ubuntu LTS release is scheduled for the 26th of April and I would suggest upgrading once that release is out. If your research computer is using tools that have not been updated for 2 years, this may be missing important bug fixes that affect your experiments.

**Comment by FoivosMichelinakis** [comment]
Thank you @irl . I think this is the best approach. If somebody wants to use the module, he can make sure it is installed and the rest do not have to have this dependency.

**Comment by ana-cc** [comment]
Merged PR
