### ISSUE TITLE
--cert argument unrecognized

### ISSUE THREAD

**Issue by alfs** [ana-cc/monroe-cli#4]
```
$ git rev-parse --short HEAD
1fbd904
$ monroe whoami
Please run monroe setup --cert <certificate> to be able to submit experiments and retrieve results.
$ monroe setup --cert iminds-alfredsson.p12
usage: monroe [-h] Command ...
monroe: error: unrecognized arguments: --cert
$
```

It works when excluding --cert.

```
$ monroe setup iminds-alfredsson.p12
Enter passphrase:
Your certificate files were stored in ~/.monroe
$ monroe whoami
Authentication ID: **, Name: ******, Storage Quota remaining: ******* bytes
$
```

**Comment by ana-cc** [comment]
Looks like I forgot to update the description when I re-did the
arguments. Thank you for this, will update.
Ana


On Thu, Dec 7, 2017, at 11:12 AM, Stefan A wrote:
> $ git rev-parse --short HEAD 1fbd904 $ monroe whoami Please run
> monroe setup --cert <certificate> to be able to submit experiments
> and retrieve results. $ monroe setup --cert iminds-alfredsson.p12
> usage: monroe [-h] Command ... monroe: error: unrecognized arguments:
> --cert $
>> It works when excluding --cert.


> $ monroe setup iminds-alfredsson.p12 Enter passphrase: Your
> certificate files were stored in ~/.monroe $ monroe whoami
> Authentication ID: **, Name: ******, Storage Quota remaining:
> ******* bytes $
>> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/ana-cc/monroe-cli/issues/4

**Comment by ana-cc** [comment]
Fixed the wording in the error messages.
