### ISSUE TITLE
invalid int value for --nodes argument

### ISSUE THREAD

**Issue by alfs** [ana-cc/monroe-cli#5]
```
$ monroe create --nodes 400 steven76/dennis
usage: monroe create [-h] [--name NAME] [--deployed] [--nodecount NODECOUNT]
                     [--ifcount IFCOUNT] [--maxnodes] [--duration DURATION]
                     [--start START] [--traffic TRAFFIC] [--storage STORAGE]
                     [--logfile LOGFILE] [--ssh] [--new] [--old]
                     [--jsonstr JSONSTR [JSONSTR ...]]
                     [--countries COUNTRIES [COUNTRIES ...]]
                     [--nodes NODES [NODES ...]]
                     [--recurrence <period, finish time> <period, finish time>]
                     [--availability]
                     script
monroe create: error: argument --nodes: invalid int value: 'steven76/dennis'
```

Using --nodes=400 works however, but does not allow for multiple nodes to be specified.
The argument parsing for --countries is similar, so check if this also needs adjustment.

**Comment by ana-cc** [comment]
Your syntax is incorrect. monroe create needs the container as a positional argument, whereas you've put it at the end and you're getting the error above. It should be:
monroe create steven76/dennis --nodes 123
Specify additional nodes like this:
monroe create steven76/dennis --nodes 123 124 125

**Comment by ana-cc** [comment]
Forgot something- the nodecount also needs to be set to the number of nodes when specifying multiple nodes:
monroe create steven76/dennis --nodes 123 124 125 --nodecount 3

Reopening as you should be able to specify multiple nodes without having to specify the nodecount.

**Comment by ana-cc** [comment]
...and fixed; monroe create steven76/dennis --nodes 123 124 125 will correctly submit with a nodecount of 3.

**Comment by alfs** [comment]
I see. I was tricked by the help output :)

```
                    [--nodes NODES [NODES ...]]
                    [--recurrence <period, finish time> <period, finish time>]
                    [--availability]
                    script
```

So it should be like this? Does countries and jsonstr also need to be at the end?

```
                    [--recurrence <period, finish time> <period, finish time>]
                    [--availability]
                    script
                    [--nodes NODES [NODES ...]]
```

**Comment by ana-cc** [comment]
Ah, I see now- ok I'll correct it.


On Tue, Dec 12, 2017, at 07:41 PM, Stefan A wrote:
> I see. I was tricked by the help output :)


>                     [--nodes NODES [NODES ...]] [--recurrence <period,
>                     finish time> <period, finish time>] [--
>                     availability] script
>> So it should be like this? Does --jsonstr also need to be at the end?


>                     [--recurrence <period, finish time> <period,
>                     finish time>] [--availability] script [--nodes
>                     NODES [NODES ...]]
>> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/ana-cc/monroe-cli/issues/5#issuecomment-351170954
