### ISSUE TITLE
possible parsing problem with jsonstr

### ISSUE THREAD

**Issue by alfs** [ana-cc/monroe-cli#9]
Using lists of lists seems to produce incorrect quoting when the json is passed:

```
monroe create docker.monroe-system.eu/monroe/monroe-web/image --jsonstr "http_protocols":["h1","h1s"]
"urls":[["https://www.httpvshttps.com/","http://www.kau.se"],
["http://www.kau.se","http://www.kau.se"]]

Allocated task 15677.
Additional options passed: {'http_protocols': ['h1', 'h1s'],
'urls': ['https://www.httpvshttps.com/', 'http://www.kau.se]', '[http://www.kau.se', 'http://www.kau.se']}
```
[ is included in the quoted string for the second list, and also the overarching [] are removed.

**Comment by ana-cc** [comment]
Fixed in https://github.com/ana-cc/monroe-cli/commit/6d6feb655271e6c6f003cdd41c9001b2e27d244d
The input you give the jsonstr argument needs to now be formated as JSON. Don't forget to escape your quotes inside the input string.
